### PR TITLE
first attempt at color inversion

### PR DESCRIPTION
**Pull request by pgmmpk**
added `invertColor` option to `\cuKrukPara`.

Idea is to allow this:
```
\cuKrukPara[invertColor]{ aaa \\ bbb}
```

### CODE REVIEW

**Comment by pgmmpk** [comment]
Addresses issue #55

**Comment by typiconman** [comment]
Hmm. I get an error:
``! Package xkeyval Error: no value specified for key `invertColor'.``

Here's my M(n)WE:

```
\documentclass{article}
\usepackage{polyglossia}
\usepackage{fontspec}
\usepackage{churchslavonic}
\setdefaultlanguage{churchslavonic}
\newfontfamily\churchslavonicfont[Script=Cyrillic,Ligatures=TeX]{PonomarUnicode.otf}
\newfontfamily\musicFont[Scale=1.5]{MezenetsUnicode}
\let\cuKrukFont=\musicFont
\begin{document}
\cuKruk[invertColor]{𜽰𜼅}{Тво}
\end{document}
```

**Comment by pgmmpk** [comment]
Oops. this option exists only for `\cuKrukPara`, not (yet) for `\cuKruk`. Please try with `\cuKrukPara` - seem to work here

**Comment by typiconman** [comment]
Still no luck. If I try to compile this code:
```
\documentclass{article}
\usepackage{polyglossia}
\usepackage{fontspec}
\usepackage{churchslavonic}
\setdefaultlanguage{churchslavonic}
\newfontfamily\churchslavonicfont[Script=Cyrillic,Ligatures=TeX]{PonomarUnicode.otf}
\newfontfamily\musicFont[Scale=1.5]{MezenetsUnicode}
\let\cuKrukFont=\musicFont

\begin{document}

\cuKrukPara[invertColor]{
𜽟 𜾆𜼱𜼇
\\
Хри-сто́съ
}

\end{document}
```

I get the message: ``! Package xkeyval Error: no value specified for key `invertColor'.``.

If I specify a vaue for `invertColor`, as the message suggests (e.g., `invertColor=1`), I get a different error:
``! Use of \cu@kinovar@color doesn't match its definition.``

**Comment by pgmmpk** [comment]
I see many problems there. Will need some time to review.

**Comment by typiconman** [comment]
Yes, now it works!

**Pull request merged**
