### PR TITLE
Adapt gloss file to recent polyglossia infrastructure

### LINKED ISSUE #71: Errors at gloss-churchslavonic.ldf
After `TexLive` update (onLinux Debian 12) I get errors on [sample.tex](https://www.ponomar.net/files/sample.tex?_ga=2.140987890.1988467528.1721728811-641832422.1717793103) compilation.   

Log:
```
This is XeTeX, Version 3.141592653-2.6-0.999996 (TeX Live 2024) (preloaded format=xelatex 2024.7.23)  23 JUL 2024 13:17
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**sample.tex
(./sample.tex
LaTeX2e <2024-06-01> patch level 2
L3 programming layer <2024-05-27>

<skipped>

(/home/user/texlive/2024/texmf-dist/tex/latex/polyglossia/gloss-latex.ldf
File: gloss-latex.ldf polyglossia: module for default language
))
(/home/user/texlive/2024/texmf-dist/tex/latex/churchslavonic/gloss-churchslavon
ic.ldf
File: gloss-churchslavonic.ldf polyglossia: module for Church Slavonic

! Undefined control sequence.
l.14 \define@key
                {churchslavonic}{spelling}[modern]{%
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.


! LaTeX Error: Missing \begin{document}.

```

and several similar errors:

```
! Undefined control sequence.
l.29 \define@boolkey
                    {churchslavonic}[churchslavonic@]{babelshorthands}[false]{}

! Undefined control sequence.
l.31 \setkeys
             {churchslavonic}{spelling,numerals}
```

`fmtutil-sys --byfmt xelatex` - without errors.

### PR DESCRIPTION
**Pull request by jspitz**
Fixes https://github.com/slavonic/cu-tex/issues/71

This also adds the BCP47 tags now used in polyglossia

### CODE REVIEW

**Comment by typiconman** [comment]
@pgmmpk Please review.

**Comment by pgmmpk** [comment]
Thank you for the effort, but I believe this fix is incorrect.

Dependency on xkeyval was previously introduced by polyglossia. The latest polyglossia does not load xkeyval and this caused the issue reported as #71 .

The suggested change refactors gloss file to not depend on xkeyval. However, other pieces of `churchslavonic` depend on xkeyval (transitively, via graphics). For example, `cu-kruk` sub-package. Maybe more hidden traps are there.

Correct fix would be just to add `\RequirePackage{xkeyval}` to churchslavonic STY file. For end users temporary workaround is to do `\usepackage{xkeyval}` before loading `churchslavonic`.

**Comment by jspitz** [comment]
The gloss will no longer correctly work with polyglossia without the suggested adaptations. We have shifted the whole infrastructure towards l3. If you stick with xkeyval, polyglossia won't switch to churchslavonic any longer (I was one of the persons who did that change).

If you need ykeyval in other parts of your package, load it there. But the gloss should do without it.

**Comment by pgmmpk** [comment]
Interesting approach - breaking backward compatibility and throwing out the users... 

Unless you (or someone else) rewrite graphics in l3, xkeyval is a must here. Thank you for letting us know that latest polyglossia is incompatible with the old api.

Practically, we will have to do both: load xkeyval (for the sake of graphics) and deal with polyglossia somehow...

**Comment by jspitz** [comment]
Well, I tried to help with getting churchslavonic back on track, but given the hostilities here, I withdraw my proposal

**Comment by typiconman** [comment]
I would like to see some kind of solution ...

**Comment by pgmmpk** [comment]
@typiconman 

1. Add `\RequirePackage{xkeyval}` to `churchslavonic.sty`
2. Review, test, and apply gloss changes suggested by @jspitz 

Open questions:

* Maybe graphics is already ported to L3? 
* What other packages have been changed in a backward-incompatible manner?
* How to test it end-to-end with the latest CTAN snapshot?

**Comment by pgmmpk** [comment]
The changes suggested by this PR were fully incorporated into PR #74 . Thanks, @jspitz .
Closing this PR

**Pull request closed without merging**
