### PR TITLE
Fix gloss file and package dependencies

### PR DESCRIPTION
**Pull request by pgmmpk**
Polyglossia API has changed, requiring this change. It also uncovered a problem with `xkeyval` dependency that was not declared explicitly, but was loaded via (old) polyglossia.

1. gloss file fixed (copied changes suggested by @jspitz - thanks!)
2. implicit xkeyval dependency made explicit
3. version bump

As tested, documentation was successfully compiled with LuaLaTeX, using texlive 2024, installed on a clean Ubuntu (https://www.tug.org/texlive/quickinstall.html).

### CODE REVIEW

**Comment by pgmmpk** [comment]
fixes #71

**Comment by typiconman** [comment]
Question: what happens on older versions of TeXLive? When I run make with LuaHBTeX, Version 1.17.0 (TeX Live 2023), I get this:

```
! Undefined control sequence.
l.53 \InitializeGlossOptions
                          {churchslavonic}{babelshorthands=false,

! LaTeX Error: Missing \begin{document}.
```
Or we don't need to worry about this scenario?

**Comment by pgmmpk** [comment]
AFAIK, there is no way in LaTeX to request a specific version of a package. The best we can do is to improve the error message by using `\@ifpackagelater`.

We probably should not care too much about this, because mixing sources from different texlive versions will never work.

**Comment by typiconman** [comment]
OK. Merged and closed.

**Pull request merged**
