### PR TITLE
better definition of underscore (that does not interfere with fontspec)

### PR DESCRIPTION
**Pull request by pgmmpk**
@typiconman I believe I found the solution for the underscore in font definition parameters. Please check

### CODE REVIEW

**Comment by typiconman** [comment]
I don't think it works. Try doing:

`\newfontfamily\churchslavonicfont[Script=Cyrillic,Ligatures=TeX,HyphenChar=_]{PonomarUnicode.otf}`

after calling 

`\usepackage{churchslavonic}`

**Comment by pgmmpk** [comment]
@typiconman Try this. I do not understand why it works, but it seem to do the trick. Please confirm

**Comment by typiconman** [comment]
It's still not working for me:

`.................................................
. fontspec info: "defining-font"
. 
. Font family 'PonomarUnicode.otf(0)' created for font 'PonomarUnicode.otf'
. with options [].
. 
. This font family consists of the following shapes:
. 
. \* 'normal' with NFSS spec.:
. <->"[PonomarUnicode.otf]/ICU:script=latn;language=DFLT;"
.................................................

! Missing \endcsname inserted.
<to be read again> 
                   \char 
l.39 ...ures=TeX,HyphenChar=_]{PonomarUnicode.otf}

? x
`

**Comment by typiconman** [comment]
FYI, I don't know if this is the desired behavior, but the `\cuMarginMarkText` command redefines the subsequent `\cuMarginMark`. Example:

`
\cuMarginMark{※} A small black mark
\def\cuMarginMarkText#1{\cuKinovar{#1}}
\cuMarginMark{※} A small red mark
\def\cuMarginMarkText#1{\Huge \cuKinovar{#1}}
\cuMarginMark{※} A huge red mark
`

**Comment by pgmmpk** [comment]
Yes, this is as designed. Idea is the you define font/size/color of margin marks once - in the preamble
and afterwards just use \cuMarginMark (local changes still possible via something like
\cuMarginMark{{\tiny а}}).

Since you find it surprising, lets discuss alternatives. 
What would be a better interface to allow customization of font/size/color of margin marks?

**Comment by typiconman** [comment]
No, I think this makes sense. It's just not clear from the documentation. We should document it. 
`\cuMarginMark{{\tiny а}}` makes sense as well; I think we should document it too.

**Comment by pgmmpk** [comment]
@typiconman please check the latest changes to the docs:

https://github.com/slavonic/cu-tex/pull/41/commits/edf896f4c4ca289e87cbe19d9f8702601a17798b

**Comment by typiconman** [comment]
Made a few spellings corrections and fixed a typo that was causing Make to error-out.

**Pull request merged**
