### PR TITLE
changed generator of single_patterns.txt 

### PR DESCRIPTION
**Pull request by pgmmpk**
Tried to follow the spirit of Aleksander's manual work.

Results in about 4K automatically generated patterns.

@typiconman please check if this is acceptable. Of course, this generates much more patterns than the ones that you suggested (and much more than will happen in real life). But the advantage is that
nothing is missed, as all possible combining letters with and without pokrytie, and common accents with and without breathing are listed.

### CODE REVIEW

**Comment by pgmmpk** [comment]
@typiconman note that this is on top of hyph-boundary branch, not master. If accepted, merge into hyph-boundary first, then merge the latter into master.

**Comment by typiconman** [comment]
@pgmmpk There are still some patterns that are completely impossible, like vowels with a yerok (or payerok), or the kavyka with a pokytie. But I'm fine with keeping them if it's easier. The only thing I would add is that there is an alternative spelling for ѽ as U+A64D U+0486 U+0311. But maybe it's easier to handle that at the time when we do the NFC->NFD stuff.

**Comment by pgmmpk** [comment]
@typiconman what are the alternative spellings for ѽ? I believe that U+A64D U+0486 U+0311
is already in the list? Trying to understand what did I miss.

**Comment by typiconman** [comment]
@pgmmpk Yes, I mean that we should make U+A64D U+0486 U+0311 = U+047D, even though strictly speaking it is not handled by NFD -> NFC. The same for the uppercase form U+A64C U+0486 U+0311 = U+047C. Yes, Unicode Cyrillic is a bit of a mess, unfortunately.

**Pull request merged**
