### PR TITLE
Makefile that builds fonts-churchslavonic CTAN package

### PR DESCRIPTION
**Pull request by pgmmpk**
@typiconman please review

By mistake I committed everything to the master (sorry!). Check every file in the fonts/ subdirectory, please.

### CODE REVIEW

**Comment by pgmmpk** [comment]
Also, please let me know if there other usable Unicode fonts (noto?) that should be included.

**Comment by typiconman** [comment]
Two questions:
1. The files like PonomarUnicode-specific-info.tex ... these are not standalone files, but are included by a script into a TeX file that is then compiled into PonomarUnicode.pdf. The -specific-info.tex files won't compile themselves. Maybe we should write some different font documentation that will compile?
2. Would it be easier to submodule the cu-fonts repository and just copy the fonts from there?

**Comment by pgmmpk** [comment]
1. TeX Live has very rigid policy for inclusion into their repository (they do not accept everything from CTAN). The tricky part is the requirement to provide sources for all PDFs. Yes, providing the "true"
   generated *.tex files would be cleaner. I was just lazy, hoping that this will do since this is the only
   human-written doc part... My second option was not to include *.PDF into CTAN submission...
   Can you generate those *.tex files and include them either into XXX-src.zip or commit to cu-fonts?
2. I agree that this logically belongs to cu-fonts. Lets move this Makefile there?

**Comment by typiconman** [comment]
@pgmmpk What I will do then is create the appropriate Makefile in the fonts-cu package. It could actually just build the fonts and TeX documentation from source.

**Comment by pgmmpk** [comment]
Thank you, @typiconman 

When done, please merge this PR - it will delete the accidentally committed fonts/ directory
from the master branch.

**Comment by typiconman** [comment]
@pgmmpk: please look at the work at https://github.com/typiconman/fonts-cu/pull/11

**Comment by typiconman** [comment]
Makefile and bundle created in cu-fonts project. Merging and closing.

**Pull request merged**
